### ISSUE TITLE
Ansible traefik handler deletes all configuration of the traefik container

### ISSUE THREAD

**Issue by traedamatic** [sbaerlocher/ansible.traefik#5]
Hello,
i noticed a strange behavior. When run role once on the server everything works fine. But if i only alter a configuration the traefik container results in to a none configured state. 

All volumes, exported ports and so on are gone.

I forked your repo some days ago made some changes and altered the handler definition like this:

https://github.com/konekto/ansible.traefik/commit/578ce62f8275785aa1d98008ff7d5a196d2b6129

Can your reproduce this behavior?
Best wishes,
Nicolas

**Comment by sbaerlocher** [comment]
Hello Nicolas

I can still see this behavior in myself.
Why do you define whole containers again in the ```handlers.yml```?
Because with that you create a new container, these lines should suffice in ```handlers.yml```. 

```yml
- name: restart traefik
  docker_container:
    name: webproxy
    restart: true
```

Greeting
Simon

**Comment by traedamatic** [comment]
Hallo Simon,

i think you misunderstand me. 

The implementation with just 
```
- name: restart traefik
  docker_container:
    name: webproxy
    restart: true
```
did restart the container but all configuration are missing. 

I did refactor the handler with all configuration to fix that bug.

Can you reproduce this bug:

1. Run the playbook once. 
2. Only change the configuration (traefik.toml)
3. Run the playbook again\

?

Best wishes,
Nicolas
